apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rental-gui
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rental-gui
spec:
  build:
    env:
      - # EnvVar represents an environment variable present in a
        # Container.
        # +optional
        name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-Dmaven.test.skip=true --no-transfer-progress clean package -Pproduction"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dcaron/rental-gui
      ref:
        branch: main
