apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bike-gui
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: bike-gui
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dcaron/bike-gui
      ref:
        branch: main
