apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rental-gui-second
  description: Bike Rental
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=rental-gui-second'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
